#!/bin/sh

# First argument: database hostname. We make the assumption that
# ~/.pgpass contains the necessary information to allow the connection
# to the database.
#
# Second argument: output file.
#
# This script typically needs to be executed as a cronjob

DATABASE_HOST=$(echo $1 | cut -d':' -f1)
DATABASE_PORT=$(echo $1 | cut -d':' -f2)
test -z $DATABASE_PORT && DATABASE_PORT=5432
OUTPUT_FILE=$2

echo "select last_update from maposmatic_admin;" | \
    psql -h ${DATABASE_HOST} -p ${DATABASE_PORT} -A -t > ${OUTPUT_FILE}
