#!/bin/sh

# First argument: database hostname. We make the assumption that
# ~/.pgpass contains the necessary information to allow the connection
# to the database.
#
# Second argument: output file.
#
# This script typically needs to be executed as a cronjob

DATABASE=$1
OUTPUT_FILE=$2

echo "select last_update from maposmatic_admin;" | \
    psql -h ${DATABASE} -A -t > ${OUTPUT_FILE}
